### PR TITLE
Fix #17 installExtensionFromFileUpload not working

### LINKED ISSUE #17: installExtensionFromFileUpload not working
`installExtensionFromFileUpload()` does not work, at least not for Joomla 4.4.5-dev on macOS

for line `document.getElementById('legacy-uploader').classList.remove('hidden')`

:red_circle: `cypress error Cannot read properties of null (reading 'classList')`

waiting for the element to be present, works in this environment:
```JavaScript
cy.get('#legacy-uploader').should('exist').then(($uploader) => {
    if ($uploader) {
        cy.get('#legacy-uploader').invoke('removeClass', 'hidden');
     }
});
```

I will use this in [manual-examples](https://github.com/joomla/manual-examples/tree/main/tests) first and come back later with tested PR here

### PR DESCRIPTION
**Pull request by muhme**
Error was `cypress error Cannot read properties of null (reading 'classList')`.

Fixed by waiting for the element to be present.

Tested with https://github.com/joomla/manual-examples/pull/28 on
* Intel macOS 14.5 Sonoma with branches 4.4-dev, 5.1-dev, 5.2-dev and 6.0-dev
* Microsoft Windows 11 Pro with branches 4.4-dev, 5.1-dev, 5.2-dev and 6.0-dev
* Ubuntu 24.04 Noble Numbat with branches 4.4-dev, 5.1-dev, 5.2-dev and 6.0-dev

### CODE REVIEW

File: src/extensions.js [hunk 1]
```diff
@@ -54,7 +54,12 @@ const extensionsCommands = () => {
 
     cy.contains('Upload Package File').click()
 
-    document.getElementById('legacy-uploader').classList.remove('hidden')
+    // Wait until the element is available
+    cy.get('#legacy-uploader').should('exist').then(($uploader) => {
+      if ($uploader) {
```
Comment (laoneo) [inline src/extensions.js:59]: Can it really be that it is here null? If yes, can you add a comment in which case?

Comment (muhme) [reply src/extensions.js:59]: Yes, it is `null` in all cases, backward tested 15 times always the error `TypeError: Cannot read properties of null (reading 'classList')`:

- Intel macOS 14.5 Sonoma
  - Cypress 13.10.0, Node v20.11.1
    - Electron 118 (headless) with branches 4.4-dev, 5.1-dev, 5.2-dev and 6.0-dev
    - Firefox v126 (GUI) with branch 4.4-dev
- Ubuntu 24.04 Noble Numbat
  - Cypress 13.10.0, Node v18.19.1
    - Electron 118 (headless) with branches 4.4-dev, 5.1-dev, 5.2-dev and 6.0-dev
- Microsoft Windows 11 Pro
  - Cypress 13.10.0, Node v20.13.1
    - Electron 118 (headless) with branches 4.4-dev, 5.1-dev, 5.2-dev and 6.0-dev
    - Edge 125 (GUI) with branch 4.4-dev
    - Chrome 125 (GUI) with branch 4.4-dev

My favourite comment is the way it is:
```
// Wait until the element is available
```
Or I can offer:
```
// document.getElementById('legacy-uploader').classList.remove('hidden')
// Results in TypeError: Cannot read properties of null (reading 'classList')
// Therefore, wait until the element is available
```

Comment (laoneo) [reply src/extensions.js:59]: But then we can remove that code completely inside the then function?

Comment (muhme) [reply src/extensions.js:59]: > But then we can remove that code completely inside the then function?

- no, the code inside then() is the original action and needed to remove the hidden class from #legacy-uploader to make it visible and usable
- the new inserted should('exist') ensures Cypress is waiting until the element with the ID 'legacy-uploader' exists in the DOM
- the backward tests have shown that the problem 'Cannot read properties of null' occurs everywhere where it was tested -> the fix is needed
- the code change is already in use in https://github.com/joomla/manual-examples/blob/main/tests/cypress/support/commands.js as `myInstallExtensionFromFileUpload` until new joomly-cypress NPM with this fix is available

**Comment by laoneo** [comment]
Thanks!
